# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name' : 'Crédit Bancaire',
    'version' : '17.0',
    'author': 'FINOUTSOURCE',
    'summary': 'Invoices & Payments',
    'sequence': 10,
    'description': """ Gestion des credit bancaire  """,
    'images' : [],
    'web_icon': ['credit_bancaire,static/description/icon.png'],
    'depends' : ['base', 'mail', 'account', 'account_accountant'],
    'data': [
        'security/credit_security.xml',
        'security/ir.model.access.csv',
        'data/seq_type.xml',
        'data/type_data.xml',
        'data/banque_data.xml',
        'data/saisi_donnees.xml',
        'views/credit_menu.xml',
        'views/type_credit.xml',
        'views/credit_banque.xml',
        'views/credit_autorisation.xml',
        'views/auto_global.xml',
        #'views/credit_operation.xml',
        'views/credit_disponible.xml',
        'views/credit_analyse_autorisation.xml',
        #'views/credit_analyse_operation.xml',
        'views/credit_analyse_disponible.xml',
        'views/credit_operation_deb.xml',
        'views/credit_op_deb_2.xml',
        'views/credit_op_deb_3.xml',
        'views/credit_operation_p.xml',
        'views/credit_operation_pd.xml',
        'views/credit_echeance.xml',
        'views/paiement.xml',
        'views/echeance_partiel.xml',
        'views/credit_bancaire_agence.xml',
        'views/credit_mon_agence.xml',
        'views/contacts.xml',
        'views/montage_demande_credit.xml',
        'views/montage_plan_charge.xml',
        #'views/new_model.xml',
        #'reports/bank_financing_request.xml',
        'reports/report_plan_charge.xml',
        #'wizard/create_peace_bank_views_wizard.xml'


    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
